[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
DiscreteValueIteration = "4b033969-44f6-5439-a48b-c11fa3648068"
NativeSARSOP = "a07c76ea-660d-4c9a-8028-2e6dbd212cb8"
POMDPGifs = "7f35509c-0cb9-11e9-0708-2928828cdbb7"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
QMDP = "3aa3ecc9-5a5d-57c8-8188-3e47bd8068d2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RockSample = "de008ff0-c357-11e8-3329-7fe746fe836e"
